version: '3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:v2.2.0
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    ports:
      # Expose 81 since Windows System process is using 80 ¯\_(ツ)_/¯
      - "80:80"
      # Expose 443 for TLS
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "9080:8080"
    networks:
      - traefik01
    volumes:
      # Allows Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Mount the dynamic configuration
      - ./certs-traefik.yaml:/etc/traefik/dynamic/certs-traefik.yaml
      # Mount the directory containing the certs
      - ./certs:/etc/certs/
  app1:
    image: nginx:1.17.6-alpine
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.entrypoints=web"
      - "traefik.http.routers.app1.rule=PathPrefix(`/app1{regex:$$|/.*}`)"
      - "traefik.http.routers.app1.middlewares=app1-stripprefix"
      - "traefik.http.middlewares.app1-stripprefix.stripprefix.prefixes=/app1"
    networks:
      - traefik01
  web1:
    # Configuration for building the docker image for the service
    image: web1:2.0
    container_name: "web1"
    expose:
      - 8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web1.entrypoints=websecure"
      - "traefik.http.routers.web1.rule=PathPrefix(`/web1{regex:$$|/.*}`)"
      - "traefik.http.routers.web1.middlewares=web1-stripprefix"
      - "traefik.http.routers.web1.tls=true"
      - "traefik.http.middlewares.web1-stripprefix.stripprefix.prefixes=/web1"
    networks:
      - traefik01
  web2:
    # Configuration for building the docker image for the service
    image: web2:2.0
    container_name: "web2"
    expose:
      - 8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web2.entrypoints=web"
      - "traefik.http.routers.web2.rule=PathPrefix(`/web2{regex:$$|/.*}`)"
      - "traefik.http.routers.web2.middlewares=web2-stripprefix"
      - "traefik.http.middlewares.web2-stripprefix.stripprefix.prefixes=/web2"
    networks:
      - traefik01
  app2:
    image: httpd:2.4.41-alpine
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.entrypoints=web"
      - "traefik.http.routers.app2.rule=PathPrefix(`/app2{regex:$$|/.*}`)"
      - "traefik.http.routers.app2.middlewares=app2-stripprefix"
      - "traefik.http.middlewares.app2-stripprefix.stripprefix.prefixes=/app2"
    networks:
      - traefik01
networks:
  traefik01:
    driver: bridge